name: FTP Deploy (Alternative)

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build and Deploy to FTP
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Display Node.js version
        run: |
          node -v
          npm -v
          
      - name: Install dependencies
        run: npm install
        
      - name: List files before build
        run: ls -la
        
      - name: Build application
        run: npm run build
        
      - name: List build output
        run: |
          echo "Build output directory contents:"
          ls -la dist || echo "dist directory not found"
        
      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOSTNAME }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ./
          local-dir: ./dist/
          dangerous-clean-slate: true
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            README.md
            .github/** 