name: FTP Deploy with Environment Variables

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build and Deploy to FTP
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Display Node.js version
        run: |
          node -v
          npm -v
          
      - name: Install dependencies
        run: npm install
        
      - name: Create .env file
        run: |
          echo "VITE_ALPHA_VANTAGE_API_KEY=${{ secrets.VITE_ALPHA_VANTAGE_API_KEY || 'YXIVIW837TT6I043' }}" > .env
          echo "VITE_GEMINI_API_KEY=${{ secrets.VITE_GEMINI_API_KEY || 'AIzaSyA6yvH9lgQV2kSjM76PpJ_An8u4x7HIwZ4' }}" >> .env
          echo "VITE_BREEZE_API_KEY=${{ secrets.VITE_BREEZE_API_KEY || '604718T4!d32GMS6166W21P2Mupa1449' }}" >> .env
          echo "VITE_BREEZE_API_SECRET=${{ secrets.VITE_BREEZE_API_SECRET || 'ax39y158575L189W10046N0GXWK1s060' }}" >> .env
          echo "VITE_BREEZE_SESSION_TOKEN=${{ secrets.VITE_BREEZE_SESSION_TOKEN || '1234567890' }}" >> .env
          
      - name: Build application
        run: npm run build
        
      - name: List build output
        run: |
          echo "Build output directory contents:"
          ls -la dist || echo "dist directory not found"
        
      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOSTNAME }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ./
          local-dir: ./dist/
          dangerous-clean-slate: true
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            README.md
            .github/** 